import { Lora } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";
import Footer from "./_components/Footer";

const inter = Lora({ subsets: ["latin"] });

export const metadata = {
  title: "BookMyDoctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <div className="md:px-20">
       <Header/>
       {children}
      
      </div>
      <Footer/>
      </body>
    </html>
  );
}
